export const RepositoriesTypes = {
  REPOSITORIES_REQUEST: 'REPOSITORIES_REQUEST',
  LOAD_REPOSITORIES_SUCCESS: 'LOAD_REPOSITORIES_SUCCESS',
  LOAD_REPOSITORIES_FAILURE: 'LOAD_REPOSITORIES_FAILURE',
};

export const LoginTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
};
